"use client";
import {BookMusic} from './book-music';
import {useEffect,useState} from 'react';
import {ArrowUpRight,RotateCw,BookOpen} from 'lucide-react';
import {automaticRecommendations} from '@/lib/automatic-recommendations';
import {koreanDay,type DailyPicks} from '@/lib/daily-picks';
import {safeUrl,money} from '@/lib/books';
export function AutomaticBooks({recent,onSearch}:{recent:string[];onSearch:(query:string)=>void}){
 const [offset,setOffset]=useState(0);const [daily,setDaily]=useState<DailyPicks|null>(null);const [state,setState]=useState('loading');
 useEffect(()=>{let stopped=false;let requested='';let controller:AbortController|undefined;
 const refresh=()=>{const day=koreanDay();if(requested===day)return;requested=day;controller?.abort();controller=new AbortController();setState('loading');setDaily(null);setOffset(0);fetch('/api/daily-picks',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('unavailable');const body=await r.json() as DailyPicks;if(!stopped){setDaily(body);setState('ready');}}).catch(()=>{if(!stopped){setState('fallback');requested='';}});};
 refresh();const timer=setInterval(refresh,60000);const visible=()=>{if(document.visibilityState==='visible')refresh();};document.addEventListener('visibilitychange',visible);return()=>{stopped=true;controller?.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[]);
 const fallback=automaticRecommendations(recent,offset);const items=daily?Array.from({length:Math.min(3,daily.items.length)},(_,i)=>({...daily.items[(offset+i)%daily.items.length],matched:false})):fallback.items.map(i=>({...i,topic:'',ratio:0}));
 return <div className="automatic-books"><div className="picks-heading"><div><p className="eyebrow">CURATED FOR YOUR NEXT CHAPTER</p><h2>{daily?'독서 트렌드로 고른 오늘의 책':'오늘의 발견, 세 권의 책'}<span>{String(items.length).padStart(2,'0')}</span></h2><p>{daily?`${daily.day} 추천 · ${daily.period} 주간 검색 관심도 기준`:state==='loading'?'트렌드를 확인하고 있습니다. 잠시 동안 기본 추천을 보여드려요.':'트렌드 연결이 원활하지 않아 기본 추천을 보여드립니다.'}</p></div><button className="refresh-picks" onClick={()=>setOffset(n=>n+3)}><RotateCw size={15}/>다른 책 보기</button></div><div className="picks-grid">{items.map(({book,reason,matched,topic,ratio},i)=>{const offer=book.offers.find(o=>o.available);return <article className={`pick-card pick-tone-${i}`} key={book.id}><a className="pick-art" href={safeUrl(book.sourceUrl)} target="_blank" rel="noreferrer" aria-label={`${book.title} 도서 소개 보기`}><span className="pick-number">0{i+1}</span><span className="pick-badge">{topic?`${topic} · ${ratio.toFixed(1)}`:matched?'관심 주제':'기본 추천'}</span>{book.cover?<img src={safeUrl(book.cover)} alt={`${book.title} 표지`} loading="lazy"/>:<BookOpen size={70}/>}<span className="pick-art-link"><ArrowUpRight size={19}/></span></a><div className="pick-content"><span className="category">{book.category}</span><h3>{book.title}</h3><p className="pick-author">{book.author} <span>·</span> {book.publisher}</p><div className="pick-reason"><span>이 책을 고른 이유</span><p>{reason}</p></div><BookMusic book={book}/><div className="pick-bottom"><div>{offer?<><small>YES24 수집 상품가</small><strong>{money(offer.price)}</strong><small>배송비 별도 · {new Date(offer.checkedAt!).toLocaleDateString('ko-KR')} 확인</small></>:<><small>판매가</small><strong className="unknown-price">서점에서 확인</strong></>}</div><button onClick={()=>onSearch(book.isbn||book.title)} aria-label={`${book.title} 가격과 서점 찾기`}><ArrowUpRight size={22}/></button></div></div></article>;})}</div><details className="curation-note"><summary>추천은 어떻게 골랐나요?</summary><p>네이버 데이터랩의 같은 최신 주간 관측값을 비교해 검색 관심도가 높은 분야부터 한 권씩 고릅니다. 수치는 비교 검색어 중 최대 100인 상대 검색량이며 판매량이나 오늘의 실시간 순위가 아닙니다. 미리 선정한 도서 목록에서 한국시간 날짜별로 책을 순환하며, 분야에 책이 한 권뿐이면 유지됩니다. 페이지를 열거나 열린 화면에서 날짜가 바뀌면 자동 갱신합니다. 수집 후 7일이 지난 가격은 숨깁니다.{daily&&<> 데이터 조회: {new Date(daily.fetchedAt).toLocaleString('ko-KR')}.{daily.uncovered.length>0&&` 현재 추천 도서가 없어 제외한 분야: ${daily.uncovered.join(', ')}.`}</>}</p></details></div>;
}
