"use client";
import {useState} from 'react';
import {ArrowUpRight,RotateCw,BookOpen} from 'lucide-react';
import {automaticRecommendations} from '@/lib/automatic-recommendations';
import {safeUrl,money} from '@/lib/books';
export function AutomaticBooks({recent,onSearch}:{recent:string[];onSearch:(query:string)=>void}){
 const [offset,setOffset]=useState(0);const {items,matched}=automaticRecommendations(recent,offset);
 return <div className="automatic-books"><div className="picks-heading"><div><p className="eyebrow">CURATED FOR YOUR NEXT CHAPTER</p><h2>{matched?'관심의 다음 페이지':'오늘의 발견, 세 권의 책'}<span>03</span></h2><p>{matched?'최근 검색 주제에서 한 걸음 더 들어가 보세요.':'이야기 한 권, 새로운 관점 한 권. 다음에 읽을 책을 만나보세요.'}</p></div><button className="refresh-picks" onClick={()=>setOffset(n=>n+3)}><RotateCw size={15}/>다른 책 보기</button></div><div className="picks-grid">{items.map(({book,reason,matched},i)=>{const offer=book.offers.find(o=>o.available);return <article className={`pick-card pick-tone-${i}`} key={book.id}><a className="pick-art" href={safeUrl(book.sourceUrl)} target="_blank" rel="noreferrer" aria-label={`${book.title} 도서 소개 보기`}><span className="pick-number">0{i+1}</span><span className="pick-badge">{matched?'관심 주제':'에디터스 픽'}</span>{book.cover?<img src={safeUrl(book.cover)} alt={`${book.title} 표지`} loading="lazy"/>:<BookOpen size={70}/>}<span className="pick-art-link"><ArrowUpRight size={19}/></span></a><div className="pick-content"><span className="category">{book.category}</span><h3>{book.title}</h3><p className="pick-author">{book.author} <span>·</span> {book.publisher}</p><div className="pick-reason"><span>이 책을 고른 이유</span><p>{reason}</p></div><div className="pick-bottom"><div>{offer?<><small>YES24 수집 상품가</small><strong>{money(offer.price)}</strong><small>배송비 별도 · {new Date(offer.checkedAt!).toLocaleDateString('ko-KR')} 확인</small></>:<><small>판매가</small><strong className="unknown-price">서점에서 확인</strong></>}</div><button onClick={()=>onSearch(book.isbn||book.title)} aria-label={`${book.title} 가격과 서점 찾기`}><ArrowUpRight size={22}/></button></div></div></article>;})}</div><details className="curation-note"><summary>추천은 어떻게 골랐나요?</summary><p>AI가 미리 선정한 8권에서 3권을 보여줍니다. 최근 검색 최대 5개를 이 브라우저 안에서 주제별 규칙으로 매칭해 정렬하며, 실시간 AI 분석은 아닙니다. ‘다른 책 보기’로 목록을 순환합니다. 수집 후 7일이 지난 가격은 표시하지 않습니다.</p></details></div>;
}
