'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Bookmark,Check,RotateCw} from 'lucide-react';
import {bookDates,dateRound,dateStorageKey,readDateSaves} from '@/lib/book-date';
import {safeUrl} from '@/lib/books';
import {BookMusic} from './book-music';
export function BookDate({onSearch}:{onSearch:(query:string)=>void}){
 const [offset,setOffset]=useState(0);const [selected,setSelected]=useState<string|null>(null);const [saved,setSaved]=useState<string[]>([]);const [ready,setReady]=useState(false);const [message,setMessage]=useState('');
 const heading=useRef<HTMLHeadingElement>(null);const focusReveal=useRef(false);
 useEffect(()=>{try{setSaved(readDateSaves(localStorage.getItem(dateStorageKey)));}catch{setMessage('브라우저 저장소에 접근할 수 없습니다. 책 소개팅은 계속 이용할 수 있어요.');}setReady(true);const sync=(e:StorageEvent)=>{if(e.key===dateStorageKey||e.key===null)setSaved(readDateSaves(e.newValue));};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
 useEffect(()=>{if(selected&&focusReveal.current){heading.current?.focus();focusReveal.current=false;}},[selected]);
 const match=bookDates.find(d=>d.id===selected);const round=dateRound(offset);
 function toggle(isbn:string){try{const current=readDateSaves(localStorage.getItem(dateStorageKey));const next=current.includes(isbn)?current.filter(v=>v!==isbn):[...current,isbn];localStorage.setItem(dateStorageKey,JSON.stringify(next));setSaved(next);setMessage(next.includes(isbn)?'이 브라우저에 책을 저장했어요.':'저장 목록에서 제거했어요.');}catch{setMessage('저장하지 못했어요. 브라우저의 저장소 설정을 확인해 주세요.');}}
 function next(){setSelected(null);setOffset(n=>n+3);setMessage('');}
 return <section className="book-date"><header className="date-heading"><div><p className="eyebrow">A QUESTION BEFORE A TITLE</p><h2>표지 없이, 마음이 먼저 고르는 책</h2><p>끌리는 질문 하나를 골라보세요. 어떤 책인지는 선택한 뒤 공개합니다.</p></div><button className="refresh-picks" onClick={next}><RotateCw size={15}/>다른 질문 만나기</button></header>
 {!match?<div className="date-questions">{round.map((d,i)=><button className={`date-question date-tone-${i}`} key={d.id} onClick={()=>{focusReveal.current=true;setSelected(d.id);setMessage('');}}><span>QUESTION 0{i+1}</span><strong>{d.question}</strong><small>이 질문의 책 만나기 <ArrowUpRight size={18}/></small></button>)}</div>:<article className="date-reveal"><div className="date-cover">{match.book.cover&&<img src={safeUrl(match.book.cover)} alt={`${match.book.title} 표지`} width="180" height="270"/>}</div><div><span className="category">당신이 고른 질문</span><p className="date-chosen">“{match.question}”</p><h3 ref={heading} tabIndex={-1}>{match.book.title}</h3><p className="help">{match.book.author} · {match.book.publisher}</p><p className="date-reason">{match.note}</p><p className="date-excerpt">{match.book.description.slice(0,260)}{match.book.description.length>260?'…':''}</p><a className="text-button" href={safeUrl(match.book.sourceUrl)} target="_blank" rel="noreferrer">도서 소개 출처 확인 ↗</a><BookMusic key={match.id} book={match.book}/><div className="date-actions"><button className="date-save" disabled={!ready} aria-pressed={saved.includes(match.book.isbn)} onClick={()=>toggle(match.book.isbn)}>{saved.includes(match.book.isbn)?<Check size={17}/>:<Bookmark size={17}/>} {saved.includes(match.book.isbn)?'저장됨 · 취소':'읽고 싶은 책으로 저장'}</button><button className="detail" onClick={()=>onSearch(match.book.isbn)}>가격·서점 찾기 <ArrowUpRight size={17}/></button><a className="text-button" href={`/books/${match.book.isbn}`}>책 상세 보기</a></div><button className="text-button date-back" onClick={()=>setSelected(null)}>같은 질문으로 돌아가기</button></div></article>}
 <p className="help date-disclosure">질문은 도서 소개의 주제를 바탕으로 작성한 창작 문구이며, 책의 직접 인용이나 AI 성격 진단이 아닙니다.</p><p className="date-message" role="status">{message}</p>
 <section className="date-saved" aria-label="소개팅에서 저장한 책"><h3>다시 만나고 싶은 책 <span>{saved.length}</span></h3><p className="help">이 브라우저에만 저장됩니다. 브라우저 데이터를 지우면 목록도 삭제됩니다.</p>{ready&&saved.length===0?<p className="date-empty">마음에 드는 책을 공개한 뒤 저장해 보세요.</p>:<ul>{saved.map(isbn=>{const d=bookDates.find(d=>d.book.isbn===isbn)!;return <li key={isbn}><div><a href={`/books/${isbn}`}>{d.book.title}</a><small>{d.book.author}</small></div><button className="text-button" onClick={()=>{focusReveal.current=true;setSelected(d.id);}}>다시 보기</button><button className="text-button" aria-label={`${d.book.title} 저장 취소`} onClick={()=>toggle(isbn)}>저장 취소</button></li>;})}</ul>}</section></section>;
}
