"use client";
import {useState,useRef,useEffect} from 'react';
import {Search,ArrowUpRight} from 'lucide-react';
import type {discoverySearch,SearchMode} from '@/lib/discovery';
import {safeUrl} from '@/lib/books';
const modes:{id:SearchMode;title:string;example:string}[]=[{id:'situation',title:'상황으로',example:'퇴근길 20분 동안 읽을 가벼운 책'},{id:'taste',title:'취향으로',example:'『불편한 편의점』처럼 따뜻하지만 덜 슬픈 소설'},{id:'purpose',title:'목적으로',example:'경제를 처음 배우는데 수식은 싫어요'},{id:'memory',title:'기억으로',example:'편의점에서 일하는 사람이 나오는 한국 소설'}];
export function SentenceSearch({onSearch}:{onSearch:(q:string)=>void}){
 const [mode,setMode]=useState<SearchMode>('situation');const [query,setQuery]=useState('');const [result,setResult]=useState<ReturnType<typeof discoverySearch>|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const sequence=useRef(0);const abort=useRef<AbortController|null>(null);useEffect(()=>()=>abort.current?.abort(),[]);
 async function search(e:React.FormEvent){e.preventDefault();const seq=++sequence.current;abort.current?.abort();abort.current=new AbortController();setBusy(true);setResult(null);setError('');try{const r=await fetch(`/api/discovery?mode=${mode}&q=${encodeURIComponent(query)}`,{signal:abort.current.signal});const body=await r.json() as ReturnType<typeof discoverySearch>&{error?:string};if(!r.ok)throw new Error(body.error);if(seq===sequence.current)setResult(body);}catch(e){if(seq===sequence.current)setError(e instanceof Error?e.message:'검색 오류');}finally{if(seq===sequence.current)setBusy(false);}}
 return <details className="sentence-search"><summary><span>제목을 몰라도 괜찮아요.</span> 문장으로 책 찾기 <ArrowUpRight size={17}/></summary><div className="sentence-body"><div className="sentence-modes" aria-label="검색 방식">{modes.map(m=><button key={m.id} aria-pressed={mode===m.id} onClick={()=>{++sequence.current;abort.current?.abort();setBusy(false);setMode(m.id);setQuery(m.example);setResult(null);setError('');}}>{m.title} 찾기</button>)}</div><form onSubmit={search}><label htmlFor="sentence-query">어떤 책을 찾고 있나요?</label><textarea id="sentence-query" maxLength={300} minLength={2} required value={query} onChange={e=>setQuery(e.target.value)} placeholder={modes.find(m=>m.id===mode)!.example}/><button type="submit" disabled={busy||query.trim().length<2}><Search size={16}/>{busy?'소개에서 단서를 찾고 있어요':'문장으로 찾기'}</button></form><p className="help">공개 도서 소개의 문구를 비교합니다. 짧은 소개로 확인할 수 없는 조건은 판단하지 않습니다.</p>{error&&<p role="alert" className="error">{error}</p>}<div aria-live="polite">{result&&<><p className="help">{result.totalRecords}권에서 찾은 {result.results.length}개 후보 · {result.coverage}</p>{result.warnings.map(w=><p className="help" key={w}>{w}</p>)}{!result.results.length&&<p className="sentence-empty">소개에서 일치하는 근거를 찾지 못했습니다. ‘편의점’, ‘경제 입문’처럼 핵심 단어로 다시 찾아보세요.</p>}<div className="sentence-results">{result.results.map(({book,labels,evidence,matchedTerms})=><article key={book.isbn}><div><span className="category">{labels.join(' · ')||matchedTerms.join(' · ')}</span><h3>{book.title}</h3><p className="help">{book.author} · {book.publisher}</p><blockquote>{evidence}…</blockquote><p className="help">출처의 소개 문구이며, 모든 조건을 충족한다는 뜻은 아닙니다.</p><div className="recommend-links"><a href={safeUrl(book.sourceUrl)} target="_blank" rel="noreferrer" className="text-button">소개 원문 확인 ↗</a><button className="text-button" onClick={()=>onSearch(book.isbn)}>가격·서점 찾기 ↗</button></div></div>{book.cover&&<img src={safeUrl(book.cover)} alt={`${book.title} 표지`} loading="lazy"/>}</article>)}</div></>}</div></div></details>;
}
