'use client';
import {useEffect,useState} from 'react';
import {BookOpen,Download,NotebookPen} from 'lucide-react';
import {reasons,needs,reflectionGuide,reflectionKey,readReflections,addReflection,type WorkReflection} from '@/lib/work-reflection';
export function WorkReflectionPanel({onSearch}:{onSearch:(query:string)=>void}){
 const [reason,setReason]=useState<string>('people'),[need,setNeed]=useState<string>('comfort');
 const [note,setNote]=useState(''),[rows,setRows]=useState<WorkReflection[]>([]),[ready,setReady]=useState(false),[message,setMessage]=useState('');
 const guide=reflectionGuide(reason,need);
 useEffect(()=>{try{setRows(readReflections(localStorage.getItem(reflectionKey)));}catch{setMessage('저장소를 읽지 못했습니다. 브라우저 설정을 확인해 주세요.');}setReady(true);const sync=(e:StorageEvent)=>{if(e.key===reflectionKey||e.key===null)setRows(readReflections(e.newValue));};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync);},[]);
 useEffect(()=>{if(!note.trim())return;const leave=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[note]);
 function save(e:React.FormEvent){e.preventDefault();try{const next=addReflection(readReflections(localStorage.getItem(reflectionKey)),{id:crypto.randomUUID(),reason:guide.reason.id,need:guide.need.id,note,createdAt:new Date().toISOString()});localStorage.setItem(reflectionKey,JSON.stringify(next));setRows(next);setNote('');setMessage('오늘의 생각을 이 브라우저에 저장했습니다.');}catch(e){setMessage(e instanceof Error&&e.message.includes('100개')?e.message:'저장하지 못했습니다. 입력 내용과 브라우저 저장소를 확인해 주세요.');}}
 function remove(id:string){if(!window.confirm('이 기록을 삭제할까요? 삭제한 기록은 되돌릴 수 없습니다.'))return;try{const next=readReflections(localStorage.getItem(reflectionKey)).filter(r=>r.id!==id);localStorage.setItem(reflectionKey,JSON.stringify(next));setRows(next);setMessage('기록을 삭제했습니다.');}catch{setMessage('삭제하지 못했습니다. 다시 시도해 주세요.');}}
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(rows,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='agentbook-work-reflections.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="work-reflection"><header><p className="eyebrow">AFTER WORK</p><h2>퇴근 후 마음 정리</h2><p>남을지 떠날지 결정하기 전에, 지금 내게 필요한 것부터 살펴봐요.</p></header><div className="reflection-layout"><div className="reflection-main"><fieldset><legend>01 · 지금 무엇이 힘든가요?</legend><div className="reflection-options">{reasons.map(r=><button key={r.id} aria-pressed={reason===r.id} onClick={()=>setReason(r.id)}>{r.label}</button>)}</div></fieldset><fieldset><legend>02 · 오늘은 어떤 도움이 필요한가요?</legend><div className="reflection-options">{needs.map(n=><button key={n.id} aria-pressed={need===n.id} onClick={()=>setNeed(n.id)}>{n.label}</button>)}</div></fieldset><div className="reflection-action"><span>오늘의 작은 행동</span><h3>{guide.action}</h3><p>{guide.reason.prompt}</p></div><form onSubmit={save}><label htmlFor="work-reflection-note">03 · 내 생각 남기기</label><textarea id="work-reflection-note" maxLength={1000} required rows={5} value={note} onChange={e=>setNote(e.target.value)} placeholder="오늘 있었던 일, 내 감정, 다음에 해보고 싶은 일을 적어보세요."/><div className="reflection-save"><small>{note.length}/1,000자</small><button disabled={!ready||!note.trim()}><NotebookPen size={16}/>생각 저장</button></div></form></div><aside className="reflection-aside"><BookOpen size={24}/><h3>다른 관점이 필요할 때</h3><p>선택한 상황과 도움을 바탕으로 <strong>‘{guide.query}’</strong> 관련 책을 찾아보세요.</p><button className="reflection-search" onClick={()=>onSearch(guide.query)}>관련 책 찾기 →</button><p className="reflection-caption">기록 내용은 검색에 사용하지 않습니다. 선택한 주제만 도서 검색으로 전달됩니다.</p><hr/><h3>결정은 나의 속도로</h3><p>이곳은 생각을 정리하는 공간입니다. 퇴사 여부를 평가하거나 정답을 정해주지 않아요.</p></aside></div><p role="status" className="journal-message">{message}</p><section className="reflection-history"><div className="reflection-history-head"><h3>내 마음 돌아보기 <small>{rows.length}/100</small></h3><button onClick={download} disabled={!rows.length}><Download size={16}/>기록 내려받기</button></div>{rows.length>0?<><p className="reflection-caption">저장한 기록의 상황별 횟수 · 마음 상태에 대한 진단이 아닙니다.</p><div className="reflection-counts">{reasons.map(r=><span key={r.id}>{r.label} <b>{rows.filter(row=>row.reason===r.id).length}</b></span>)}</div><ol>{rows.map(row=><li key={row.id}><div><time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleDateString('ko-KR')}</time><span>{reasons.find(r=>r.id===row.reason)?.label} · {needs.find(n=>n.id===row.need)?.label}</span><button onClick={()=>remove(row.id)} aria-label={`${new Date(row.createdAt).toLocaleDateString('ko-KR')} 기록 삭제`}>삭제</button></div><p>{row.note}</p></li>)}</ol></>:<p>아직 기록이 없어요. 오늘의 생각 한 줄부터 시작해 보세요.</p>}</section><p className="reflection-caption">기록은 이 브라우저에만 저장됩니다. 브라우저 데이터를 삭제하면 사라지며 다른 기기와 동기화되지 않습니다. 내려받은 파일에도 기록 내용이 포함됩니다.</p></section>;
}
